### ISSUE TITLE
Xcode Compilation Error

### ISSUE THREAD

**Issue by hFrNa** [jacul/TumblrDownload#1]
Hello,

It seems there're some problems with TumblrDownload or my compilation steps. I got an error when I tried building from code.
The error showed in Xcode as below (after clicking the BUILD button):
<img width="1047" alt="screenshot 2016-05-30 23 25 04" src="https://cloud.githubusercontent.com/assets/16957227/15653253/6b45136a-26be-11e6-964c-c962601a5d45.png">

Does TumblrDownload have some issues? Or my steps were wrong?
Thank you!

**Comment by jacul** [comment]
It's because the workspace was not present, you can generate it by doing "pod install" after installing CocoaPods. I pushed it to the repository, you should be able to open "TumblrDownload.xcworkspace" and build from there.
